[project]
name = "rnnbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "botclient",
]

[tool.uv.sources]
botclient = { git = "https://github.com/spikelynch/botclient" }
